#include <ecuInfo.h>
#include <communication.h>
#include <lcd.h>

// Fingerprint database, generated by disassembling the SCI dispatch of each
// ROM in mh6111_project/roms/. Source of truth:
//   mh6111_project/reference/ROM_fingerprint_table.md
//
// t_strap3 in each ROM has 4 slots. The E931 source comments label them as
// (Fwd Federal, Fwd California, Awd Federal, Awd California) -- consistent with
// DSM market taxonomy. Non-US ROMs (EDM/JDM) may reuse those 4 slots for
// different markets; the labels here follow the DSM convention as a best
// guess. Where a strap word matches no slot, we display "?" so a user with a
// known-good vehicle can correct the mapping.

const char ROM_E742_NAME[] PROGMEM      = "E742 (1G AWD Turbo)";
const char ROM_E766_NAME[] PROGMEM      = "E766";
const char ROM_E799_NAME[] PROGMEM      = "E799";
const char ROM_E931_NAME[] PROGMEM      = "E931 (GVR4/DSM MT)";
const char ROM_E932_NAME[] PROGMEM      = "E932 (GVR4/DSM AT)";
const char ROM_E935_NAME[] PROGMEM      = "E935";
const char ROM_E44228B5_NAME[] PROGMEM  = "E44228B5 (NA)";
const char ROM_UNKNOWN_NAME[] PROGMEM   = "Unknown";

const char SLOT_FWD_FED[] PROGMEM = "Fwd Fed";
const char SLOT_FWD_CAL[] PROGMEM = "Fwd Cal";
const char SLOT_AWD_FED[] PROGMEM = "Awd Fed";
const char SLOT_AWD_CAL[] PROGMEM = "Awd Cal";
const char SLOT_UNKNOWN[] PROGMEM = "?";

const char PROBING[] PROGMEM = "Probing ECU...";
const char NO_RESPONSE[] PROGMEM = "ECU not responding";
const char ECU_INFO_HEADER[] PROGMEM = "ECU Info";
const char ROM_LABEL[] PROGMEM = "ROM";
const char STRAP_LABEL[] PROGMEM = "Straps";
const char CFG_LABEL[] PROGMEM = "Cfg";

struct rom_entry {
    uint8_t  id_byte;
    const char *name PROGMEM;
    uint16_t slot[4];
};

// One row per unique ROM. Slot values are the 16-bit words at t_strap3
// as they appear in the ROM (big-endian in the source .word directive).
const rom_entry romTable[] PROGMEM = {
    {0x14, ROM_E935_NAME,     {0xE025, 0xE025, 0x1412, 0x201E}},
    {0x36, ROM_E742_NAME,     {0xE022, 0xE023, 0x272F, 0x0348}},
    {0x46, ROM_E44228B5_NAME, {0xE086, 0xE087, 0xE086, 0xE087}},
    {0x4F, ROM_E766_NAME,     {0xE025, 0xE025, 0x0303, 0x1412}},
    {0x61, ROM_E799_NAME,     {0xE020, 0xE021, 0x030B, 0x4001}},
    {0xB5, ROM_E931_NAME,     {0xE022, 0xE023, 0xE022, 0xE023}},
    {0xB7, ROM_E932_NAME,     {0xE022, 0xE023, 0xE022, 0xE023}},
};

const uint8_t ROM_TABLE_SIZE = sizeof(romTable) / sizeof(*romTable);

const char *const slotLabels[4] PROGMEM = {
    SLOT_FWD_FED, SLOT_FWD_CAL, SLOT_AWD_FED, SLOT_AWD_CAL
};

// Query one obdCode, return COMM_ERR on timeout/echo mismatch.
static int probe(int code) {
    return getResponseFromAddr(code);
}

// Find the ROM entry index for a given $FD byte. Returns -1 if unknown.
static int findRomByIdByte(uint8_t id) {
    for (uint8_t i = 0; i < ROM_TABLE_SIZE; i++) {
        uint8_t stored = pgm_read_byte(&romTable[i].id_byte);
        if (stored == id) return i;
    }
    return -1;
}

// Given a ROM index and a 16-bit strap word, find which of the 4 slots matches.
// Tries both byte orderings because empirical byte order of $FE/$FF is not
// yet confirmed at the wire level. Returns -1 if no match.
static int findStrapSlot(int romIdx, uint16_t strap_be, uint16_t strap_le) {
    for (uint8_t s = 0; s < 4; s++) {
        uint16_t val = pgm_read_word(&romTable[romIdx].slot[s]);
        if (val == strap_be || val == strap_le) return s;
    }
    return -1;
}

static void printLineP(const char *label_P, const char *value, uint8_t row) {
    char labelBuf[8];
    strncpy_P(labelBuf, label_P, sizeof(labelBuf) - 1);
    labelBuf[sizeof(labelBuf) - 1] = '\0';
    char line[LCD_COLS + 1];
    snprintf(line, sizeof(line), "%s: %s", labelBuf, value);
    printResult(line, row);
}

void showEcuInfo() {
    clearScreen();
    printHeader(ECU_INFO_HEADER);

    char probeMsg[LCD_COLS];
    strcpy_P(probeMsg, PROBING);
    printResult(probeMsg, 1);

    // Empty any junk left over from Serial.begin's boot noise
    while (Serial.available()) Serial.read();
    delay(50);

    int romId = probe(0xFD);
    int strapA = probe(0xFE);
    int strapB = probe(0xFF);

    clearScreen();
    printHeader(ECU_INFO_HEADER);

    if (romId == COMM_ERR || strapA == COMM_ERR || strapB == COMM_ERR) {
        char msg[LCD_COLS];
        strcpy_P(msg, NO_RESPONSE);
        printResult(msg, 1);
        delay(3000);
        return;
    }

    int idx = findRomByIdByte((uint8_t) romId);

    // Line 1: "ROM: <name> ($XX)"
    char romLine[LCD_COLS + 1];
    if (idx >= 0) {
        char name[20];
        strncpy_P(name, (const char *) pgm_read_word(&romTable[idx].name), sizeof(name) - 1);
        name[sizeof(name) - 1] = '\0';
        snprintf(romLine, sizeof(romLine), "%s ($%02X)", name, romId);
    } else {
        char name[10];
        strcpy_P(name, ROM_UNKNOWN_NAME);
        snprintf(romLine, sizeof(romLine), "%s ($%02X)", name, romId);
    }
    printLineP(ROM_LABEL, romLine, 1);

    // Line 2: "Straps: $XXYY"  (both bytes as a big-endian word display)
    uint16_t strap_be = ((uint16_t) strapA << 8) | (uint16_t) strapB;
    uint16_t strap_le = ((uint16_t) strapB << 8) | (uint16_t) strapA;
    char strapLine[12];
    snprintf(strapLine, sizeof(strapLine), "$%02X%02X", strapA, strapB);
    printLineP(STRAP_LABEL, strapLine, 2);

    // Line 3: "Cfg: <slot name>"  -- only if we recognize the ROM
    char cfgLine[LCD_COLS + 1];
    if (idx >= 0) {
        int slot = findStrapSlot(idx, strap_be, strap_le);
        if (slot >= 0) {
            char sname[10];
            strncpy_P(sname, (const char *) pgm_read_word(&slotLabels[slot]), sizeof(sname) - 1);
            sname[sizeof(sname) - 1] = '\0';
            snprintf(cfgLine, sizeof(cfgLine), "%s", sname);
        } else {
            snprintf(cfgLine, sizeof(cfgLine), "unknown slot");
        }
    } else {
        snprintf(cfgLine, sizeof(cfgLine), "-- ROM unknown --");
    }
    printLineP(CFG_LABEL, cfgLine, 3);

    delay(3000);
}
